version: '3'
services:
  service:
    image: cmdb
    restart: on-failure
    healthcheck:
      test: curl localhost:8000
      interval: 30s
      timeout: 1s
      retries: 1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        example: 1
