# Generated by Django 3.2.2 on 2021-06-07 13:10

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', 'V0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('IP', models.CharField(db_index=True, max_length=128, verbose_name='IP')),
                ('Hostname', models.CharField(max_length=128, verbose_name='Hostname')),
                ('PublicIp', models.CharField(blank=True, max_length=128, null=True, verbose_name='Public IP')),
                ('Number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Asset number')),
                ('CreatedBy', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('Comment', jsonfield.fields.JSONField(null=True, verbose_name='Comment')),
                ('CPU', models.FloatField(null=True, verbose_name='CPU')),
                ('Memory', models.FloatField(null=True, verbose_name='CPU')),
                ('DiskInfo', jsonfield.fields.JSONField(null=True, verbose_name='DiskInfo')),
                ('Ports', jsonfield.fields.JSONField(null=True, verbose_name='Ports')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Asset',
                'permissions': [('view_self_asset', 'Can view self assets')],
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Asset Group',
                'verbose_name_plural': 'Asset Group',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, verbose_name='Name')),
                ('Value', models.CharField(max_length=128, verbose_name='Value')),
                ('Comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Label',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('Name', models.SlugField(allow_unicode=True, unique=True, verbose_name='Name')),
                ('Comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platform',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('Protocol', models.CharField(max_length=64, verbose_name='Protocol')),
                ('Port', models.IntegerField(verbose_name='Port')),
            ],
            options={
                'verbose_name': 'Protocol',
                'verbose_name_plural': 'Protocol',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('Username', models.CharField(max_length=64, verbose_name='Username')),
                ('Password', models.TextField(null=True, verbose_name='Password')),
                ('LastPassword', models.TextField(default='', null=True, verbose_name='Last Password')),
                ('Key', models.TextField(null=True, verbose_name='Key')),
                ('Protocols', models.ManyToManyField(to='asset.Protocol', verbose_name='Protocol')),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System User',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64, verbose_name='Name')),
                ('Asset', models.ManyToManyField(default=None, to='asset.Asset')),
                ('AssetGroup', models.ManyToManyField(default=None, to='asset.AssetGroup')),
                ('SystemUser', models.ManyToManyField(to='asset.SystemUser')),
            ],
            options={
                'verbose_name': 'Asset Permission',
                'verbose_name_plural': 'Asset Permission',
            },
        ),
    ]
