# Generated by Django 3.2.2 on 2021-06-07 13:10

import asset.models.platform
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0001_asset_assetgroup_label_permission_platform_protocol_systemuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='User',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permission',
            name='UserGroup',
            field=models.ManyToManyField(default=None, to='user.Group'),
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='Assets',
            field=models.ManyToManyField(to='asset.Asset', verbose_name='Assets'),
        ),
        migrations.AddField(
            model_name='asset',
            name='Labels',
            field=models.ManyToManyField(blank=True, related_name='assets', to='asset.Label', verbose_name='Labels'),
        ),
        migrations.AddField(
            model_name='asset',
            name='Platform',
            field=models.ForeignKey(default=asset.models.platform.Platform.default, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='asset.platform', verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='asset',
            name='Protocols',
            field=models.ManyToManyField(to='asset.Protocol', verbose_name='Protocol'),
        ),
    ]
