# Generated by Django 3.2.2 on 2021-06-07 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', 'V0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, verbose_name='Name')),
                ('SubDomain', models.CharField(default='', max_length=128, null=True, verbose_name='Domain')),
                ('Domain', models.CharField(max_length=128, verbose_name='Domain')),
                ('Status', models.CharField(max_length=128, null=True, verbose_name='Status')),
                ('ExpireDate', models.DateTimeField(null=True, verbose_name='Expire Date')),
                ('DnsServer', models.TextField(null=True, verbose_name='DNS Server')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domain',
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Prefix', models.CharField(max_length=128, verbose_name='Prefix')),
                ('Type', models.CharField(max_length=128, verbose_name='Type')),
                ('Value', models.CharField(max_length=128, verbose_name='Value')),
                ('MxPriority', models.IntegerField(null=True, verbose_name='MX Priority')),
                ('Circuit', models.CharField(max_length=128, null=True, verbose_name='Circuit')),
                ('Weight', models.IntegerField(null=True, verbose_name='Weight')),
                ('TTL', models.IntegerField(verbose_name='TTL')),
                ('LastUpdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update')),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.domain')),
            ],
            options={
                'verbose_name': 'DNS Record',
                'verbose_name_plural': 'DNS Record',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, verbose_name='Name')),
                ('Domain', models.CharField(max_length=128, null=True, verbose_name='Domain')),
                ('Status', models.CharField(max_length=128, null=True, verbose_name='Status')),
                ('ExpireDate', models.DateTimeField(null=True, verbose_name='Expire Date')),
                ('Password', models.CharField(max_length=128, null=True, verbose_name='Password')),
                ('Cert', models.BinaryField(default=None, null=True, verbose_name='Cert')),
                ('FDomain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificate',
            },
        ),
    ]
