# Generated by Django 3.2.2 on 2021-06-07 13:10

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', 'V0'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=32, verbose_name='Class')),
                ('Function', models.CharField(max_length=32, verbose_name='Function')),
                ('SourceIP', models.CharField(max_length=32, verbose_name='Source IP')),
                ('URI', models.CharField(max_length=1024, verbose_name='URI')),
                ('StatusCode', models.IntegerField(null=True, verbose_name='Status Code')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'ApiLog',
                'verbose_name_plural': 'ApiLog',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('Name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('Configuration', jsonfield.fields.JSONField(null=True, verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
