BB BBBBBB
    XXXX
        BBB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB
            XXXX
                BBB BBBBBBBBBB BB BBBBBBBBBBB
                    XX XXXXXXXXXXXXX
                BBBBBB
            XXXXX
        BBBBBB
    XXXXX
BBBB
    XXXXX XXXXX XXX XXXXXXXXXXXXXX
BBBBB