# Generated by Django 3.1.7 on 2021-03-04 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', 'V0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('Name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('Configuration', jsonfield.fields.JSONField(null=True, verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=32, verbose_name='Class')),
                ('Function', models.CharField(max_length=32, verbose_name='Function')),
                ('SourceIP', models.CharField(max_length=32, verbose_name='Source IP')),
                ('URI', models.CharField(max_length=1024, verbose_name='URI')),
                ('StatusCode', models.IntegerField(null=True, verbose_name='Status Code')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'ApiLog',
                'verbose_name_plural': 'ApiLog',
            },
        ),
    ]
