"""
Django settings for Django project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import configparser
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent.parent

if not os.path.isfile(os.path.join(BASE_DIR, 'config.ini')):
    print("Please create config.ini first")
    exit(1)

CONFIG = configparser.RawConfigParser()
CONFIG.read(os.path.join(BASE_DIR, 'config.ini'))

if 'DJANGO' not in CONFIG:
    exit(1)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CONFIG.get('DJANGO', 'SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = CONFIG.getboolean('DJANGO', 'DEBUG')
ALLOWED_HOSTS = list(filter(None, str.split(CONFIG.get('DJANGO', 'ALLOWED_HOSTS', fallback=''), ',')))
ALLOWED_HOSTS.append('127.0.0.1')

# Application definition


INSTALLED_APPS = [
    'reversion',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'management.urls'

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'
DJANGO_TITLE = CONFIG.get('DJANGO', 'TITLE', fallback='DJANGO')
