"""
Django settings for cmdb project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import configparser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

if not os.path.isfile(os.path.join(BASE_DIR, 'config.ini')):
    print("Please create config.ini first")
    exit(1)
config = configparser.ConfigParser()
config.read(os.path.join(BASE_DIR, 'config.ini'))

if 'DJANGO' not in config:
    exit(1)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get('DJANGO', 'SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.getboolean('DJANGO', 'DEBUG')
ALLOWED_HOSTS = list(filter(None, str.split(config.get('DJANGO', 'ALLOWED_HOSTS', fallback=''), ',')))
ALLOWED_HOSTS.append('127.0.0.1')

# Application definition


INSTALLED_APPS = [
    'reversion',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cmdb',
    'asset',
    'audits',
    'domain',
    'pages',
    'user',
    'service'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]
ROOT_URLCONF = 'cmdb.urls'

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'
DJANGO_TITLE = config.get('DJANGO', 'TITLE', fallback='Power CMDB')
