# Generated by Django 3.2.4 on 2021-06-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='publicKey',
            field=models.TextField(null=True),
        ),
    ]
